// The counter corpus: what staff really type, and what the engine must read from
// it. Lowercase, no punctuation, fields in any order. sweep.mjs runs every line.
//
// Each case:
//   u      the utterance
//   a      expected action            s   expected receipt subtype
//   op     expected timesheet op
//   f      expected field values (strings compare case-insensitively; null means
//          the field must be empty)
//   has    field must contain this text: { supply: 'paper' }
//   items  expected shipment items, in order (only the keys given are checked)
//   keys   expected key items as "2xKW1"
//   pack   expected packing item count (0 = none)
//   segs   how many actions the splitter must find (default: not checked)
//   attach expected side actions: { pay: true, label: true }
//   known  a string saying why this one is a documented gap (reported, not failed)
export const CORPUS = [
  // Action-led names and mistyped UPS numbers from the counter.
  { u: 'receipt Sarah fisher halifax 4038362888 1Z97377252837 $33.45 ups express saver', a: 'receipt', s: 'shipping', f: { customerName: 'Sarah Fisher', customerPhone: '4038362888' }, items: [{ courier: 'UPS Express Saver', trackingNumber: '1Z97377252837', city: 'Halifax', province: 'NS', cost: 33.45 }] },
  { u: 'receipt Sarah fisher halifax 4038362888 1Z999AA10123456784 $33.45 ups express saver', a: 'receipt', s: 'shipping', f: { customerName: 'Sarah Fisher', customerPhone: '4038362888' }, items: [{ courier: 'UPS Express Saver', trackingNumber: '1Z999AA10123456784', city: 'Halifax', province: 'NS', cost: 33.45 }] },
  { u: 'ups to calgary 1z12345678 25', a: 'receipt', s: 'shipping', f: { customerName: null, customerPhone: null }, items: [{ courier: 'UPS', trackingNumber: '1Z12345678', city: 'Calgary', province: 'AB', cost: 25 }] },
  { u: 'ship to calgary 1zAB1234567890CD 25', a: 'receipt', s: 'shipping', f: { customerName: null, customerPhone: null }, items: [{ courier: 'UPS', trackingNumber: '1ZAB1234567890CD', city: 'Calgary', province: 'AB', cost: 25 }] },
  { u: 'receipt mike chen toronto 4035551212 fedex 28', a: 'receipt', s: 'shipping', f: { customerName: 'Mike Chen', customerPhone: '4035551212' }, items: [{ courier: 'FedEx', trackingNumber: '', city: 'Toronto', province: 'ON', cost: 28 }] },
  { u: 'ship anna lee calgary purolator 19.50', a: 'receipt', s: 'shipping', f: { customerName: 'Anna Lee' }, items: [{ courier: 'Purolator', trackingNumber: '', city: 'Calgary', province: 'AB', cost: 19.50 }] },
  { u: 'shipping anna lee 4035551212 ups 19.50', a: 'receipt', s: 'shipping', f: { customerName: 'Anna Lee', customerPhone: '4035551212' }, items: [{ courier: 'UPS', trackingNumber: '', cost: 19.50 }] },
  { u: 'receipt blue pens 4.50', a: 'receipt', s: 'supplies', f: { customerName: null, trackingNumber: null, price: 4.50 } },
  { u: 'sale 2 binders 12', a: 'receipt', s: 'supplies', f: { customerName: null, trackingNumber: null, quantity: 2, price: 12 } },
  // Messy counter input.
  {"u": "need 3 copies of my mailbox key please", "a": "receipt", "s": "key", "f": {"keyModel": "mailbox key"}},
  {"u": "lady wants 4 copies of her house key", "a": "receipt", "s": "key", "f": {"keyModel": "house key"}},
  {"u": "cut 2 keys", "a": "receipt", "s": "key", "f": {"keyModel": "key"}},

  {"u": "ups to 123 # toronto 22", "a": "receipt", "s": "shipping", "items": [{"cost": 22, "city": "Toronto"}]},
  {"u": "ups to paris united states 45", "a": "receipt", "s": "shipping", "items": [{"city": "Paris", "country": "United States", "province": "", "cost": 45}]},
  {"u": "ups to berlin germany 45", "a": "receipt", "s": "shipping", "items": [{"city": "Berlin", "country": "Germany", "province": "", "cost": 45}]},
  {"u": "reciept kw1", "a": "receipt", "s": "key", "keys": ["1xKW1"]},
  {"u": "recipt kw1", "a": "receipt", "s": "key", "keys": ["1xKW1"]},
  {"u": "receit kw1", "a": "receipt", "s": "key", "keys": ["1xKW1"]},
  {"u": "reciet kw1", "a": "receipt", "s": "key", "keys": ["1xKW1"]},
  {"u": "recept kw1", "a": "receipt", "s": "key", "keys": ["1xKW1"]},
  {"u": "shiping ups to toronto 22", "a": "receipt", "s": "shipping", "items": [{"city": "Toronto", "cost": 22}]},
  {"u": "trakcing 1234567890", "a": "track", "f": {"trackingNumber": "1234567890"}},
  {"u": "trackng 1234567890", "a": "track", "f": {"trackingNumber": "1234567890"}},
  {"u": "inventry kw1 in stock", "a": "inventory", "f": {"inStock": true}},
  {"u": "refill for actually hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for no hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for wait hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for oops hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for sorry hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for um hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for uh hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for ok hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for okay hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for nvm hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for instead hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for cancel hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for swap hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for delete hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for remove hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for change hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for please hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for pls hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for thanks hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for une hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for pour hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for refil hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for reffil hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for reciept hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for shiping hp 65 $34", "a": "receipt", "s": "refill", "f": {"customerName": null}},
  {"u": "refill for inventry hp 65 $34", "a": "inventory", "f": {"customerName": null}},
  {"u": "note ups website is down", "a": "note", "f": {"content": "ups website is down"}},
  {"u": "note how do i print a receipt", "a": "note", "f": {"content": "how do i print a receipt"}},
  {"u": "note sue hours missing", "a": "note", "f": {"content": "sue hours missing"}},
  {"u": "ups to calgary 2 box $5", "a": "receipt", "s": "shipping", "items": [{"cost": 2, "city": "Calgary"}]},
  {"u": "ORD-ABC123 picked up", "a": "cartridge_status", "f": {"status": "picked_up"}},
  {"u": "ORD-ABC123 collected", "a": "cartridge_status", "f": {"status": "picked_up"}},
  {"u": "can you make a receipt", "a": "unknown"},
  {"u": "how can i make a label", "a": "unknown"},
  {"u": "dupe y1", "a": "receipt", "s": "key", "keys": ["1xY1"]},
  {"u": "dup sc1", "a": "receipt", "s": "key", "keys": ["1xSC1"]},
  {"u": "need 3 copies of my mailbox key please", "a": "receipt", "s": "key", "f": {"keyModel": "mailbox key"}, "keys": ["3xMailbox Key"], "known": "described keys use keyModel only; counts need a slip field or described key item support"},
  {"u": "could you give me a receipt for a house key", "a": "receipt", "s": "key", "f": {"keyModel": "house key"}},
  {"u": "refill hp 65 31", "a": "receipt", "s": "refill", "f": {"model": "65", "price": 31}},
  {"u": "refill 65 $31", "a": "receipt", "s": "refill", "f": {"model": "65", "price": 31}},
  {"u": "ups to edmonton ab t5j 0n3 24", "a": "receipt", "s": "shipping", "items": [{"cost": 24, "city": "Edmonton", "province": "AB"}]},

  {"u": "ship to 123 main st toronto on m5v 2t6 ups 22", "a": "receipt", "s": "shipping", "items": [{"cost": 22, "city": "Toronto", "province": "ON"}]},
  {"u": "ups to 456 oak avenue toronto on m5v2t6 22", "a": "receipt", "s": "shipping", "items": [{"cost": 22, "city": "Toronto", "province": "ON"}]},
  {"u": "2 toronto ups 22", "a": "receipt", "s": "shipping", "items": [{"cost": 22, "city": "Toronto"}]},
  {"u": "ship 2 toronto ups 22", "a": "receipt", "s": "shipping", "items": [{"cost": 22, "city": "Toronto"}]},
  {"u": "ups to toronot 22", "a": "receipt", "s": "shipping", "items": [{"city": "Toronot", "province": "", "cost": 22}]},
  {"u": "ship ups to toronot 22", "a": "receipt", "s": "shipping", "items": [{"city": "Toronot", "province": "", "cost": 22}]},
  {"u": "ups to new york 45", "a": "receipt", "s": "shipping", "items": [{"city": "New York", "province": "", "cost": 45}]},
  {"u": "ship ups to new york 45", "a": "receipt", "s": "shipping", "items": [{"city": "New York", "province": "", "cost": 45}]},
  {"u": "dhl to london uk 88", "a": "receipt", "s": "shipping", "items": [{"city": "London", "province": "", "country": "United Kingdom", "cost": 88}]},
  {"u": "dhl to london england 88", "a": "receipt", "s": "shipping", "items": [{"city": "London", "province": "", "country": "United Kingdom", "cost": 88}]},
  {"u": "dhl to london usa 88", "a": "receipt", "s": "shipping", "items": [{"city": "London", "province": "", "country": "United States", "cost": 88}]},
  {"u": "dhl to london france 88", "a": "receipt", "s": "shipping", "items": [{"city": "London", "province": "", "country": "France", "cost": 88}]},
  {"u": "ups to st johns nl 51", "a": "receipt", "s": "shipping", "items": [{"city": "St. John's", "province": "NL", "cost": 51}]},
  {"u": "ups to st john's nl 51", "a": "receipt", "s": "shipping", "items": [{"city": "St. John's", "province": "NL", "cost": 51}]},
  {"u": "ups to O'Leary 22", "a": "receipt", "s": "shipping", "items": [{"city": "O'Leary"}]},
  {"u": "bubble mailer 2.50 x4", "a": "receipt", "s": "supplies", "f": {"supply": "bubble mailer", "quantity": 4, "price": 2.5}},
  {"u": "bubble mailer 2.50 qty 4", "a": "receipt", "s": "supplies", "f": {"supply": "bubble mailer", "quantity": 4, "price": 2.5}},
  {"u": "cut key sc1 two of em", "a": "receipt", "s": "key", "keys": ["2xSC1"]},
  {"u": "cut sc1 two of them", "a": "receipt", "s": "key", "keys": ["2xSC1"]},
  {"u": "guy wants padlock key x2 m1", "a": "receipt", "s": "key", "keys": ["2xM1"]},
  {"u": "cut key x2 m1", "a": "receipt", "s": "key", "keys": ["2xM1"]},
  {"u": "KW1 KW1 KW1", "a": "receipt", "s": "key", "keys": ["3xKW1"]},
  {"u": "cut kw1 kw1 kw1", "a": "receipt", "s": "key", "keys": ["3xKW1"]},
  {"u": "kw1 kw1 sc1", "a": "receipt", "s": "key", "keys": ["2xKW1", "1xSC1"]},
  {"u": "cut kw1 kw1 sc1", "a": "receipt", "s": "key", "keys": ["2xKW1", "1xSC1"]},
  {"u": "dupe sc4", "a": "receipt", "s": "key", "keys": ["1xSC4"]},
  {"u": "dup kw1", "a": "receipt", "s": "key", "keys": ["1xKW1"]},
  {"u": "duplicate sc1", "a": "receipt", "s": "key", "keys": ["1xSC1"]},
  {"u": "copy of kw1", "a": "receipt", "s": "key", "keys": ["1xKW1"]},
  {"u": "lady wants 4 copies of her house key", "a": "receipt", "s": "key", "f": {"keyModel": "house key"}, "keys": ["4xHouse Key"], "known": "described keys use keyModel only; counts need a slip field or described key item support"},
  {"u": "need a mailbox key cut $6", "a": "receipt", "s": "key", "f": {"keyModel": "mailbox key"}},
  {"u": "can u make me a reciept for a key", "a": "receipt", "s": "key", "f": {"keyModel": "key"}},
  {"u": "cut 2 keys", "a": "receipt", "s": "key", "f": {"keyModel": "key"}, "keys": ["2xKey"], "known": "described keys use keyModel only; counts need a slip field or described key item support"},
  {"u": "key copy", "a": "receipt", "s": "key", "f": {"keyModel": "key"}},
  {"u": "refil hp 564 xl color 31", "a": "receipt", "s": "refill", "f": {"model": "564XL", "price": 31, "customerName": null}},
  {"u": "reffil hp 564 xl color 31", "a": "receipt", "s": "refill", "f": {"model": "564XL", "price": 31, "customerName": null}},
  {"u": "refill hp 564 xxl color 31", "a": "receipt", "s": "refill", "f": {"model": "564XXL", "price": 31, "customerName": null}},
  {"u": "h p 65 refill", "a": "receipt", "s": "refill", "f": {"model": "65", "price": null}},
  {"u": "refill 65", "a": "receipt", "s": "refill", "f": {"model": "65", "price": null}},
  {"u": "refill 63", "a": "receipt", "s": "refill", "f": {"model": "63", "price": null}},
  {"u": "ORD-ABC123 is ready for pickup", "a": "cartridge_status", "f": {"status": "ready"}},
  {"u": "ORD-ABC123 ready to pick up", "a": "cartridge_status", "f": {"status": "ready"}},
  {"u": "ORD-ABC123 ready to be picked up", "a": "cartridge_status", "f": {"status": "ready"}},
  {"u": "show me orders not picked up", "a": "cartridge_list"},
  {"u": "list refills waiting", "a": "cartridge_list"},
  {"u": "what refills are ready", "a": "cartridge_list"},
  {"u": "whats the status of sarahs refill", "a": "cartridge_list"},
  {"u": "any refills for sarah", "a": "cartridge_list"},
  {"u": "sarahs refill", "a": "receipt", "s": "refill", "f": {"customerName": "Sarah"}},
  {"u": "sarah's refill", "a": "receipt", "s": "refill", "f": {"customerName": "Sarah"}},
  {"u": "how many hours did sue work this week", "a": "timesheet", "op": "view", "f": {"employeeName": "Sue"}},
  {"u": "sue's hours this week", "a": "timesheet", "op": "view", "f": {"employeeName": "Sue"}},
  {"u": "hours for sue", "a": "timesheet", "op": "view", "f": {"employeeName": "Sue"}},
  {"u": "hours for mike", "a": "timesheet", "op": "view", "f": {"employeeName": "Mike"}},
  {"u": "cancel mikes shift tomorrow", "a": "timesheet", "f": {"employeeName": "Mike"}},
  {"u": "cancel mike's shift tomorrow", "a": "timesheet", "f": {"employeeName": "Mike"}},
  {"u": "swap sue and mike on friday", "a": "timesheet", "f": {"employeeName": "Sue"}, "segs": 1},
  {"u": "swap sue and mike shifts friday", "a": "timesheet", "f": {"employeeName": "Sue"}, "segs": 1},
  {"u": "open the ups site", "a": "directory"},
  {"u": "link for fedex pickup", "a": "directory"},
  {"u": "whats the staples website", "a": "directory"},
  {"u": "moneris login", "a": "directory"},
  {"u": "ups website", "a": "directory"},
  {"u": "fedex login page", "a": "directory"},
  {"u": "how do i print a receipt", "a": "unknown"},
  {"u": "how do you make a label", "a": "unknown"},
  {"u": "what can you do", "a": "unknown"},
  {"u": "can you email receipts", "a": "unknown"},
  {"u": "email receipt to sarah@gmail.com", "a": "unknown"},
  {"u": "22", "a": "unknown"},
  {"u": "got 50 kw1 blanks in", "a": "inventory", "f": {"inStock": true}},
  {"u": "received 10 hp 65", "a": "inventory", "f": {"inStock": true}},
  {"u": "20 kw1 came in", "a": "inventory", "f": {"inStock": true}},

  // --- Lookups: a question about stock, price or where a key hangs ---------------
  { u: 'price of canon PC-211', a: 'inventory_lookup', f: { model: 'PC-211' } },
  { u: 'price of samsung MLT-D111S', a: 'inventory_lookup', f: { model: 'MLT-D111S' } },
  { u: 'kw1', a: 'inventory_lookup', has: { query: 'kw1' } },
  { u: 'KW1?', a: 'inventory_lookup' },
  { u: 'do we have sc1', a: 'inventory_lookup', has: { query: 'sc1' } },
  { u: 'how much is a kw1', a: 'inventory_lookup', has: { query: 'kw1' } },
  { u: 'price of hp 65', a: 'inventory_lookup', f: { brand: 'HP', model: '65' } },
  { u: 'is the 564xl in stock', a: 'inventory_lookup', has: { query: '564xl' } },
  { u: 'hp 65 in stock?', a: 'inventory_lookup' },
  { u: 'where is kw1', a: 'inventory_lookup', has: { query: 'kw1' } },
  { u: 'wheres the sc4', a: 'inventory_lookup', has: { query: 'sc4' } },
  { u: 'kw1 price', a: 'inventory_lookup', has: { query: 'kw1' } },
  { u: 'got any y1', a: 'inventory_lookup', has: { query: 'y1' } },
  { u: 'do we carry brother tn660', a: 'inventory_lookup', f: { brand: 'Brother', model: 'TN660' } },
  { u: 'how much for a canon 245', a: 'inventory_lookup', f: { brand: 'Canon', model: '245' } },
  { u: 'whats the price on sc1', a: 'inventory_lookup', has: { query: 'sc1' } },
  { u: 'which slot is kw1 in', a: 'inventory_lookup', has: { query: 'kw1' } },
  { u: 'any epson 220 left', a: 'inventory_lookup', f: { brand: 'Epson', model: '220' } },
  { u: 'check stock hp 61', a: 'inventory_lookup', f: { brand: 'HP', model: '61' } },
  { u: 'how many kw1 do we have', a: 'inventory_lookup', has: { query: 'kw1' } },
  { u: 'is there any tn760', a: 'inventory_lookup', has: { query: 'tn760' } },

  // --- Key cutting --------------------------------------------------------------
  { u: '4xKW1', a: 'receipt', s: 'key', keys: ['4xKW1'] },
  { u: '2xSC4', a: 'receipt', s: 'key', keys: ['2xSC4'] },
  { u: 'duplicate WR5 four times', a: 'receipt', s: 'key', keys: ['4xWR5'] },
  { u: 'copy KW1 three times', a: 'receipt', s: 'key', keys: ['3xKW1'] },
  { u: 'KW1 qty=3', a: 'receipt', s: 'key', keys: ['3xKW1'] },
  { u: 'KW1 qty 6', a: 'receipt', s: 'key', keys: ['6xKW1'] },
  { u: 'SC4 quantity 2', a: 'receipt', s: 'key', keys: ['2xSC4'] },
  { u: 'SC1 (3)', a: 'receipt', s: 'key', keys: ['3xSC1'] },
  { u: 'WR5 (2)', a: 'receipt', s: 'key', keys: ['2xWR5'] },
  { u: 'kw1 $5 sc1 $6', a: 'receipt', s: 'key', keys: ['1xKW1', '1xSC1'], f: { price: 11 } },
  { u: '2 kw1 $4 wr5 $7', a: 'receipt', s: 'key', keys: ['2xKW1', '1xWR5'], f: { price: 15 } },
  { u: '2 kw1', a: 'receipt', s: 'key', keys: ['2xKW1'] },
  { u: 'cut a kw1', a: 'receipt', s: 'key', keys: ['1xKW1'] },
  { u: 'cut 2 sc1', a: 'receipt', s: 'key', keys: ['2xSC1'] },
  { u: 'kw1 x2', a: 'receipt', s: 'key', keys: ['2xKW1'] },
  { u: '2x kw1', a: 'receipt', s: 'key', keys: ['2xKW1'] },
  { u: 'two kw1s', a: 'receipt', s: 'key', keys: ['2xKW1'] },
  { u: '3 keys kw1', a: 'receipt', s: 'key', keys: ['3xKW1'] },
  { u: 'key copy sc1', a: 'receipt', s: 'key', keys: ['1xSC1'] },
  { u: '2 kw1 and a y1', a: 'receipt', s: 'key', keys: ['2xKW1', '1xY1'], segs: 1 },
  { u: 'customer wants 2 sc1 and 1 kw1 cut', a: 'receipt', s: 'key', keys: ['2xSC1', '1xKW1'], segs: 1 },
  { u: 'house key copy $4', a: 'receipt', s: 'key', f: { price: 4 }, has: { keyModel: 'house key' } },
  { u: 'cut a key $3.50', a: 'receipt', s: 'key', f: { price: 3.5 } },
  { u: 'receipt kw1', a: 'receipt', s: 'key', keys: ['1xKW1'] },
  { u: 'kw1 sc1 y1', a: 'receipt', s: 'key', keys: ['1xKW1', '1xSC1', '1xY1'] },
  { u: '2 kw1s 1 y1 and 2 sc4s', a: 'receipt', s: 'key', keys: ['2xKW1', '1xY1', '2xSC4'], segs: 1 },
  { u: 'made 3 copies of a kw1', a: 'receipt', s: 'key', keys: ['3xKW1'] },
  { u: 'mailbox key 5 bucks', a: 'receipt', s: 'key', f: { price: 5 }, has: { keyModel: 'mailbox key' } },
  { u: 'duplicate kw1 for dave', a: 'receipt', s: 'key', keys: ['1xKW1'], f: { customerName: 'Dave' } },

  // --- Refill receipts ----------------------------------------------------------
  { u: 'refill samsung MLT-D111S $40', a: 'receipt', s: 'refill', f: { model: 'MLT-D111S', price: 40 } },
  { u: 'refill canon PC-211 $35', a: 'receipt', s: 'refill', f: { model: 'PC-211', price: 35 } },
  { u: 'refill hp 65 for Zoë Martin', a: 'receipt', s: 'refill', f: { customerName: 'Zoë Martin' } },
  { u: 'refill canon 240 for Élodie Roy', a: 'receipt', s: 'refill', f: { customerName: 'Élodie Roy' } },
  { u: 'refill hp65 $34, 564XL', a: 'receipt', s: 'refill', segs: 1, f: { model: '65', price: 34 } },
  { u: 'refill canon 240 $30, 241XL', a: 'receipt', s: 'refill', segs: 1 },
  { u: 'refill hp 910 qty 3 $81', a: 'receipt', s: 'refill', f: { quantity: 3 }, known: 'refill slips have no quantity field' },
  { u: 'refill canon 240 quantity 2 $60', a: 'receipt', s: 'refill', f: { quantity: 2 }, known: 'refill slips have no quantity field' },
  { u: 'refill hp 65 for sarah $34', a: 'receipt', s: 'refill', f: { brand: 'HP', model: '65', price: 34, customerName: 'Sarah' }, keys: [] },
  { u: 'toner refill brother tn660 $45 403 555 1212', a: 'receipt', s: 'refill', f: { brand: 'Brother', model: 'TN660', price: 45, customerPhone: '403 555 1212' } },
  { u: 'refilled canon 245 black 25 bucks', a: 'receipt', s: 'refill', f: { brand: 'Canon', model: '245', price: 25 } },
  { u: 'hp 61xl refill 30', a: 'receipt', s: 'refill', f: { brand: 'HP', model: '61XL', price: 30 } },
  { u: 'refill for mike epson 220 $28 no tax', a: 'receipt', s: 'refill', f: { customerName: 'Mike', brand: 'Epson', model: '220', price: 28, gst: false } },
  { u: 'ink refill hp 63 tri color $32 for Dana White', a: 'receipt', s: 'refill', f: { model: '63', price: 32, customerName: 'Dana White' } },
  { u: 'refill for Sarah, HP 65, $34', a: 'receipt', s: 'refill', f: { customerName: 'Sarah', brand: 'HP', model: '65', price: 34 }, segs: 1 },
  { u: 'refill hp 65 $34 charge her card and print a label', a: 'receipt', s: 'refill', f: { price: 34 }, attach: { pay: true, label: true }, segs: 1 },
  { u: 'refill hp 65 34.99', a: 'receipt', s: 'refill', f: { model: '65', price: 34.99 } },
  { u: 'brother tn760 refill for amy 587-555-0199 $50', a: 'receipt', s: 'refill', f: { brand: 'Brother', model: 'TN760', customerName: 'Amy', customerPhone: '587-555-0199', price: 50 } },
  { u: 'refill lexmark 100xl 22 dollars tax included', a: 'receipt', s: 'refill', f: { brand: 'Lexmark', model: '100XL', price: 22 } },

  // --- Refill records (a drop-off to work on later) -----------------------------
  { u: 'intake: Vera left Canon 240', a: 'cartridge_create', f: { customerName: 'Vera', brand: 'Canon', model: '240' } },
  { u: 'intake: Noah brought HP 65', a: 'cartridge_create', f: { customerName: 'Noah', brand: 'HP', model: '65' } },
  { u: 'new order for mike hp 61 black 403-555-1212', a: 'cartridge_create', f: { customerName: 'Mike', brand: 'HP', model: '61', customerPhone: '403-555-1212' } },
  { u: 'sarah dropped off an hp 65 for refill', a: 'cartridge_create', f: { customerName: 'Sarah', brand: 'HP', model: '65' } },
  { u: 'record a refill for John Lee canon 245', a: 'cartridge_create', f: { customerName: 'John Lee', brand: 'Canon', model: '245' } },
  { u: 'log an order brother tn760 for amy 587 555 0199', a: 'cartridge_create', f: { customerName: 'Amy', brand: 'Brother', model: 'TN760', customerPhone: '587 555 0199' } },
  { u: 'customer left 2 cartridges hp 62 for pickup tomorrow name is priya', a: 'cartridge_create', f: { customerName: 'Priya', brand: 'HP', model: '62' } },
  { u: 'drop off epson 288 for raj 4035550000', a: 'cartridge_create', f: { customerName: 'Raj', brand: 'Epson', model: '288', customerPhone: '4035550000' } },
  { u: 'mark ORD-AB12CD ready', a: 'cartridge_status', f: { orderId: 'ORD-AB12CD', status: 'ready' } },
  { u: 'ord-ab12cd picked up', a: 'cartridge_status', f: { orderId: 'ORD-AB12CD', status: 'picked_up' } },
  { u: 'order ORD-XY34ZT is done', a: 'cartridge_status', f: { orderId: 'ORD-XY34ZT', status: 'ready' } },
  { u: 'show open orders', a: 'cartridge_list' },
  { u: 'pending refills', a: 'cartridge_list' },
  { u: 'list refills', a: 'cartridge_list' },
  { u: 'what orders are ready', a: 'cartridge_list' },

  // --- Shipping -----------------------------------------------------------------
  { u: 'two parcels UPS: to Prince George BC $27 and to Kamloops BC $25', a: 'receipt', s: 'shipping', segs: 1, items: [{ courier: 'UPS', city: 'Prince George', province: 'BC', cost: 27 }, { courier: 'UPS', city: 'Kamloops', province: 'BC', cost: 25 }] },
  { u: 'two parcels fedex to Edmonton $20 and Calgary $30', a: 'receipt', s: 'shipping', items: [{ courier: 'FedEx', city: 'Edmonton', cost: 20 }, { courier: 'FedEx', city: 'Calgary', cost: 30 }] },
  { u: 'ups to St. Albert AB $22', a: 'receipt', s: 'shipping', items: [{ city: 'St. Albert', province: 'AB', cost: 22 }] },
  { u: "ups to St. John's NL $25", a: "receipt", s: "shipping", items: [{ city: "St. John's", province: "NL" }] },
  { u: 'ups to Fort St. John BC $30', a: 'receipt', s: 'shipping', items: [{ city: 'Fort St. John', province: 'BC' }] },
  { u: 'ups to toronto 22', a: 'receipt', s: 'shipping', items: [{ courier: 'UPS', city: 'Toronto', province: 'ON', cost: 22 }], keys: [] },
  { u: 'UPS to Toronto ON $22', a: 'receipt', s: 'shipping', items: [{ courier: 'UPS', city: 'Toronto', province: 'ON', cost: 22 }] },
  { u: 'fedex ground calgary ab 18.50', a: 'receipt', s: 'shipping', items: [{ courier: 'FedEx Ground', city: 'Calgary', province: 'AB', cost: 18.5 }] },
  { u: 'purolator express to vancouver bc $45.99 for jane smith', a: 'receipt', s: 'shipping', f: { customerName: 'Jane Smith' }, items: [{ courier: 'Purolator Express', city: 'Vancouver', province: 'BC', cost: 45.99 }] },
  { u: 'canada post xpresspost halifax ns 32', a: 'receipt', s: 'shipping', items: [{ courier: 'Canada Post Xpresspost', city: 'Halifax', province: 'NS', cost: 32 }] },
  { u: 'ship ups 1Z999AA10123456784 to toronto $22', a: 'receipt', s: 'shipping', items: [{ courier: 'UPS', trackingNumber: '1Z999AA10123456784', city: 'Toronto', province: 'ON', cost: 22 }], keys: [] },
  { u: 'ups toronto 22, fedex vancouver 30, purolator montreal 18', a: 'receipt', s: 'shipping', segs: 1, items: [{ courier: 'UPS', city: 'Toronto', province: 'ON', cost: 22 }, { courier: 'FedEx', city: 'Vancouver', province: 'BC', cost: 30 }, { courier: 'Purolator', city: 'Montreal', province: 'QC', cost: 18 }] },
  { u: 'ups to toronto $22 and fedex to calgary $30', a: 'receipt', s: 'shipping', segs: 1, items: [{ courier: 'UPS', cost: 22 }, { courier: 'FedEx', city: 'Calgary', province: 'AB', cost: 30 }] },
  { u: 'Hannah Lemmington UPS Express Saver Toronto ON 53$ 4167382277', a: 'receipt', s: 'shipping', f: { customerName: 'Hannah Lemmington', customerPhone: '4167382277' }, items: [{ courier: 'UPS Express Saver', city: 'Toronto', province: 'ON', cost: 53 }] },
  { u: 'ups to toronto $22 box $5', a: 'receipt', s: 'shipping', items: [{ cost: 22 }], pack: 1 },
  { u: 'box $5 ups to toronto $22', a: 'receipt', s: 'shipping', items: [{ cost: 22 }], pack: 1 },
  { u: 'ups to toronto 22 with a large box', a: 'receipt', s: 'shipping', items: [{ cost: 22 }], pack: 1 },
  { u: 'ups to toronto $22 and a box $5', a: 'receipt', s: 'shipping', items: [{ cost: 22 }], pack: 1, segs: 1 },
  { u: 'fedex to edmonton 19.99 for sarah 780-555-0101', a: 'receipt', s: 'shipping', f: { customerName: 'Sarah', customerPhone: '780-555-0101' }, items: [{ courier: 'FedEx', city: 'Edmonton', province: 'AB', cost: 19.99 }] },
  { u: 'shipping to winnipeg purolator 27 dollars', a: 'receipt', s: 'shipping', items: [{ courier: 'Purolator', city: 'Winnipeg', province: 'MB', cost: 27 }] },
  { u: 'dhl to regina sk $64 tracking 1234567890', a: 'receipt', s: 'shipping', f: { customerPhone: null }, items: [{ courier: 'DHL', trackingNumber: '1234567890', city: 'Regina', province: 'SK', cost: 64 }] },
  { u: 'ups 22 toronto', a: 'receipt', s: 'shipping', items: [{ courier: 'UPS', city: 'Toronto', cost: 22 }] },
  { u: 'parcel to red deer 12.50 canada post', a: 'receipt', s: 'shipping', items: [{ courier: 'Canada Post', city: 'Red Deer', province: 'AB', cost: 12.5 }] },
  { u: 'ups to toronto', a: 'receipt', s: 'shipping', items: [{ courier: 'UPS', city: 'Toronto', province: 'ON', cost: null }] },
  { u: 'fedex 30', a: 'receipt', s: 'shipping', items: [{ courier: 'FedEx', cost: 30 }] },
  { u: 'ups ground to saskatoon $41 no tax', a: 'receipt', s: 'shipping', f: { gst: false }, items: [{ courier: 'UPS Ground', city: 'Saskatoon', province: 'SK', cost: 41 }] },
  { u: 'ups to toronto 22\nfedex to calgary 30', a: 'receipt', s: 'shipping', segs: 1, items: [{ courier: 'UPS', cost: 22 }, { courier: 'FedEx', cost: 30 }] },
  { u: 'ups $53 toronto fedex $33 calgary', a: 'receipt', s: 'shipping', items: [{ courier: 'UPS', city: 'Toronto', cost: 53 }, { courier: 'FedEx', city: 'Calgary', cost: 33 }] },
  { u: 'purolator to montreal qc 1 box 28', a: 'receipt', s: 'shipping', items: [{ courier: 'Purolator', city: 'Montreal', province: 'QC' }], known: 'a bare "1 box 28" cannot say whether 28 is the box or the shipping' },
  { u: 'ups to toronto on 22', a: 'receipt', s: 'shipping', items: [{ courier: 'UPS', city: 'Toronto', province: 'ON', cost: 22 }] },
  { u: 'ups to vancouver 35 for John Carter 604 555 0188', a: 'receipt', s: 'shipping', f: { customerName: 'John Carter', customerPhone: '604 555 0188' }, items: [{ courier: 'UPS', city: 'Vancouver', province: 'BC', cost: 35 }] },

  // --- Tracking -----------------------------------------------------------------
  { u: 'track ups 1Z999AA10123456784', a: 'track', f: { courier: 'UPS', trackingNumber: '1Z999AA10123456784' } },
  { u: '1Z999AA10123456784', a: 'track', f: { trackingNumber: '1Z999AA10123456784' } },
  { u: 'fedex 123456789012', a: 'track', f: { courier: 'FedEx', trackingNumber: '123456789012' } },
  { u: 'where is fedex 123456789012', a: 'track', f: { courier: 'FedEx', trackingNumber: '123456789012' } },
  { u: 'purolator', a: 'track', f: { courier: 'Purolator' } },
  { u: 'ups', a: 'track', f: { courier: 'UPS' } },
  { u: 'canada post LM123456789CA', a: 'track', f: { courier: 'Canada Post', trackingNumber: 'LM123456789CA' } },
  { u: 'trace 1Z999AA10123456784', a: 'track' },
  { u: 'ups 1z999aa10123456784', a: 'track', f: { courier: 'UPS', trackingNumber: '1Z999AA10123456784' } },
  { u: 'wheres my package 1Z999AA10123456784', a: 'track' },
  { u: 'purolator 331234567890', a: 'track', f: { courier: 'Purolator', trackingNumber: '331234567890' } },

  // --- Sales --------------------------------------------------------------------
  { u: 'binder clips qty 2 $6.75', a: 'receipt', s: 'supplies', f: { quantity: 2, price: 6.75, supply: 'binder clips' } },
  { u: 'paper clips qty=3 $4.50', a: 'receipt', s: 'supplies', f: { quantity: 3, price: 4.5, supply: 'paper clips' } },
  { u: 'sold a phone case for $10', a: 'receipt', s: 'supplies', f: { price: 10, supply: 'phone case' } },
  { u: 'sold 2 packs of paper 12.99', a: 'receipt', s: 'supplies', f: { price: 12.99, quantity: 2 }, has: { supply: 'paper' } },
  { u: 'customer bought a usb cable $15', a: 'receipt', s: 'supplies', f: { price: 15, supply: 'usb cable' } },
  { u: 'sale 3 pens 4.50', a: 'receipt', s: 'supplies', f: { price: 4.5, quantity: 3, supply: 'pens' } },
  { u: '20 copies $5', a: 'receipt', s: 'supplies', f: { price: 5, quantity: 20 }, has: { supply: 'copies' } },
  { u: 'printing 15 pages 3 dollars', a: 'receipt', s: 'supplies', f: { price: 3 }, has: { supply: 'print' } },
  { u: 'laminate 2 sheets $4', a: 'receipt', s: 'supplies', f: { price: 4 }, has: { supply: 'laminat' } },
  { u: 'fax 3 pages $6', a: 'receipt', s: 'supplies', f: { price: 6 }, has: { supply: 'fax' } },
  { u: 'bubble mailer 3 bucks', a: 'receipt', s: 'supplies', f: { price: 3, supply: 'bubble mailer' }, pack: 0 },
  { u: 'sold a large box $10', a: 'receipt', s: 'supplies', f: { price: 10, supply: 'large box' }, pack: 0 },
  { u: 'tape 4.99', a: 'receipt', s: 'supplies', f: { price: 4.99, supply: 'tape' } },
  { u: 'notebook 5$', a: 'receipt', s: 'supplies', f: { price: 5, supply: 'notebook' } },
  { u: 'office supplies $20', a: 'receipt', s: 'supplies', f: { price: 20 } },
  { u: 'sold 3 cups $9', a: 'receipt', s: 'supplies', f: { price: 9, quantity: 3, supply: 'cups' } },
  { u: 'membership card 10 dollars', a: 'receipt', s: 'supplies', f: { price: 10, supply: 'membership card' } },
  { u: 'colour copies 12 pages $6 for Tom Baker', a: 'receipt', s: 'supplies', f: { price: 6, customerName: 'Tom Baker' } },
  { u: 'scan to email $2', a: 'receipt', s: 'supplies', f: { price: 2 } },
  { u: 'sold a hdmi cable 12 no gst', a: 'receipt', s: 'supplies', f: { price: 12, supply: 'hdmi cable', gst: false } },
  { u: 'phone charger $18 cash', a: 'receipt', s: 'supplies', f: { price: 18, supply: 'phone charger' } },
  { u: 'sold a stapler $14 paid by card', a: 'receipt', s: 'supplies', f: { price: 14, supply: 'stapler' }, attach: { pay: true } },

  // --- Notes --------------------------------------------------------------------
  { u: 'note call sarah; she wants the hp 65', a: 'note', segs: 1, f: { content: 'call sarah; she wants the hp 65' } },
  { u: 'note phone mike; toner is ready', a: 'note', segs: 1, f: { content: 'phone mike; toner is ready' } },
  { u: 'note call sarah back tomorrow about her toner', a: 'note', f: { content: 'call sarah back tomorrow about her toner' } },
  { u: 'remember to order more kw1 blanks', a: 'note', has: { content: 'order more kw1 blanks' } },
  { u: 'remind me to call staples', a: 'note', has: { content: 'call staples' } },
  { u: 'todo fix the laminator', a: 'note', has: { content: 'fix the laminator' } },
  { u: 'note: ups pickup is late today', a: 'note', has: { content: 'ups pickup is late today' } },
  { u: 'leave a note that the fedex guy comes at 3', a: 'note', has: { content: 'the fedex guy comes at 3' } },
  { u: 'jot down printer 2 is jammed', a: 'note', has: { content: 'printer 2 is jammed' } },
  { u: 'note customer John wants 5 keys cut by friday', a: 'note', segs: 1 },
  { u: 'reminder purolator account number is 1234567', a: 'note' },
  { u: 'note call john, he wants 2 keys and a refill', a: 'note', segs: 1 },
  { u: 'note sue left her keys at the counter', a: 'note' },
  { u: 'write down that the toner shipment arrives monday', a: 'note', has: { content: 'the toner shipment arrives monday' } },

  // --- Inventory changes --------------------------------------------------------
  { u: 'no more KW10 blanks', a: 'inventory', f: { keyName: 'KW10', inStock: false } },
  { u: 'no more SC4 blanks', a: 'inventory', f: { keyName: 'SC4', inStock: false } },
  { u: 'kw1 out of stock', a: 'inventory', f: { inStock: false }, has: { keyName: 'kw1' } },
  { u: 'mark sc4 out of stock', a: 'inventory', f: { inStock: false, keyName: 'SC4' } },
  { u: 'were out of sc1', a: 'inventory', f: { inStock: false, keyName: 'SC1' } },
  { u: "we're out of hp 65", a: 'inventory', f: { inStock: false }, has: { keyName: 'hp 65' } },
  { u: 'hp 65 back in stock', a: 'inventory', f: { inStock: true }, has: { keyName: 'hp 65' } },
  { u: 'restock kw1', a: 'inventory', f: { inStock: true, keyName: 'KW1' } },
  { u: 'add kw10 to inventory', a: 'inventory', f: { keyName: 'KW10' } },
  { u: 'ran out of y1 blanks', a: 'inventory', f: { inStock: false }, has: { keyName: 'y1' } },
  { u: 'set kw1 to 10 units', a: 'inventory', has: { keyName: 'kw1' } },
  { u: 'sc1 is sold out', a: 'inventory', f: { inStock: false, keyName: 'SC1' } },

  // --- The key board ------------------------------------------------------------
  { u: 'put sc1 in b3', a: 'key_location', f: { op: 'set', position: 'B3' } },
  { u: 'move hr1 to h1', a: 'key_location', f: { op: 'set', position: 'H1' } },
  { u: 'b3 is empty', a: 'key_location', f: { op: 'clear', position: 'B3' } },
  { u: 'clear a7', a: 'key_location', f: { op: 'clear', position: 'A7' } },
  { u: 'kw1 goes in c12', a: 'key_location', f: { op: 'set', position: 'C12' } },

  // --- Directory ----------------------------------------------------------------
  { u: 'add staples.ca to directory', a: 'directory', f: { url: 'staples.ca' } },
  { u: 'bookmark canadapost.ca', a: 'directory', f: { url: 'canadapost.ca' } },
  { u: 'save link www.ups.com', a: 'directory', f: { url: 'www.ups.com' } },
  { u: 'add website https://www.purolator.com/track', a: 'directory', f: { url: 'https://www.purolator.com/track' } },

  // --- Shifts -------------------------------------------------------------------
  { u: 'who is working today', a: 'timesheet', op: 'view' },
  { u: 'whos working tomorrow', a: 'timesheet', op: 'view' },
  { u: 'who works saturday', a: 'timesheet', op: 'view' },
  { u: 'parsa 4-9 tomorrow', a: 'timesheet', op: 'add_shift', f: { employeeName: 'Parsa', start: '4:00 PM', end: '9:00 PM' } },
  { u: 'sue 10-5:30 oct 8, 9', a: 'timesheet', op: 'add_shift', f: { employeeName: 'Sue', start: '10:00 AM', end: '5:30 PM' }, segs: 1 },
  { u: 'parsa left at 8 instead of 7', a: 'timesheet', op: 'adjust_shift', f: { employeeName: 'Parsa', actualEnd: '8' } },
  { u: 'sue took a 30 min break', a: 'timesheet', op: 'adjust_shift', f: { employeeName: 'Sue', breakMinutes: 30 } },
  { u: 'johnny came in at 10:30 today', a: 'timesheet', op: 'adjust_shift', f: { employeeName: 'Johnny', actualStart: '10:30' } },
  { u: 'add employee priya', a: 'timesheet', op: 'add_employee', f: { employeeName: 'Priya' } },
  { u: 'hire employee Rowan', a: 'timesheet', op: 'add_employee', f: { employeeName: 'Rowan' } },
  { u: 'onboard employee Maya', a: 'timesheet', op: 'add_employee', f: { employeeName: 'Maya' } },
  { u: 'add shift for sue 10:75-18:00', a: 'timesheet', op: 'add_shift', f: { start: null, end: null } },
  { u: 'add shift for sue 10:00-18:65', a: 'timesheet', op: 'add_shift', f: { start: null, end: null } },
  { u: 'hours for sue this week', a: 'timesheet', op: 'view', f: { employeeName: 'Sue' } },
  { u: 'clock in dave', a: 'timesheet', op: 'punch_off' },
  { u: 'schedule for this week', a: 'timesheet', op: 'view' },
  { u: 'when does sue work', a: 'timesheet', op: 'view', f: { employeeName: 'Sue' } },
  { u: 'sue stayed till 6:30 yesterday', a: 'timesheet', op: 'adjust_shift', f: { employeeName: 'Sue', actualEnd: '6:30' } },
  { u: 'add a shift for johnny friday 12 to 5', a: 'timesheet', op: 'add_shift', f: { employeeName: 'Johnny', start: '12:00 PM', end: '5:00 PM' } },
  { u: 'parsa left at 8 and sue left at 6', a: 'timesheet', segs: 2 },
  { u: 'is sue working friday', a: 'timesheet', op: 'view', f: { employeeName: 'Sue' } },

  // --- Several things at once ---------------------------------------------------
  { u: 'refill hp 65 for sarah $34 and note she wants a call when ready', segs: 2 },
  { u: 'kw1? and who is working today', segs: 2 },
  { u: 'sold a pen $2 then track fedex 123456789012', segs: 2 },
  { u: 'mark ORD-AB12CD ready and note called the customer', segs: 2 },
  { u: 'ups to toronto $22, note customer will come back with id', segs: 2 },

  // --- Words that only look like a cue ------------------------------------------
  { u: 'sold 2 backups drives $80', a: 'receipt', s: 'supplies', f: { price: 80 } },
  { u: 'note the soundtrack cd is in the back', a: 'note' },
  { u: 'keynote print 10 pages $5', a: 'receipt', s: 'supplies', f: { price: 5 } },
  { u: 'sold a tracker tag $30', a: 'receipt', s: 'supplies', f: { price: 30 } },
  { u: 'note groups of 5 get a discount', a: 'note' },
  // --- Found by a second reader (Codex bug hunt, 2026-10-08) ----------------------
  { u: 'inventory 2 tn660 in stock', a: 'inventory', has: { keyName: 'tn660' } },
  { u: 'note restock 2 tn660 tomorrow', a: 'note' },
  { u: '2 tn660 refills $60', a: 'receipt', s: 'refill', f: { price: 60, model: 'TN660' } },
  { u: 'new order 2 tn660 for sarah $60', a: 'cartridge_create', f: { customerName: 'Sarah', model: 'TN660', price: 60 } },
  { u: 'set tn660 out of stock', a: 'inventory', f: { inStock: false }, has: { keyName: 'tn660' } },
  { u: 'ups to vancouver bc $30', a: 'receipt', s: 'shipping', items: [{ city: 'Vancouver', province: 'BC', cost: 30 }] },
  { u: 'kw1 $5 sc1 $6', a: 'receipt', s: 'key', keys: ['1xKW1', '1xSC1'] },
  { u: 'ship ups to calgary $20 tn660', a: 'receipt', s: 'shipping', keys: [], items: [{ city: 'Calgary', cost: 20 }] },
  { u: 'refill HP 65 x2 $34', a: 'receipt', s: 'refill', f: { model: '65', price: 34 }, keys: [] },
  { u: 'ship ups $22 no box', a: 'receipt', s: 'shipping', pack: 0, items: [{ cost: 22 }] },
  { u: 'ship ups $22 customer supplied box', a: 'receipt', s: 'shipping', pack: 0, f: { customerName: null }, items: [{ cost: 22 }] },
  { u: 'refill hp65 no gst $34', a: 'receipt', s: 'refill', f: { gst: false, price: 34, brand: 'HP', model: '65' } },
  { u: 'ups, 1Z999AA10123456784, to toronto, ON, $22', a: 'receipt', s: 'shipping', segs: 1, items: [{ courier: 'UPS', trackingNumber: '1Z999AA10123456784', city: 'Toronto', province: 'ON', cost: 22 }] },
  { u: 'ship ups box 4 to toronto $22', a: 'receipt', s: 'shipping', pack: 1, items: [{ cost: 22 }] },
  { u: 'sold notebook $5', a: 'receipt', s: 'supplies', f: { supply: 'notebook', price: 5 } },
  { u: 'sold membership $20', a: 'receipt', s: 'supplies', f: { supply: 'membership', price: 20 } },
  { u: 'cups $5', a: 'receipt', s: 'supplies', f: { supply: 'cups', price: 5 } },
  { u: 'backups $20', a: 'receipt', s: 'supplies', f: { price: 20 } },
  { u: 'sold 4x6 labels $5', a: 'receipt', s: 'supplies', f: { price: 5, quantity: 1, supply: '4x6 labels' } },
  { u: 'ship ups 1Z999AA10123456784 $22 phone 4035551212', a: 'receipt', s: 'shipping', f: { customerPhone: '4035551212' }, items: [{ cost: 22 }] },
  { u: 'ship dhl 1234567890 to calgary $20', a: 'receipt', s: 'shipping', f: { customerPhone: null }, items: [{ courier: 'DHL', trackingNumber: '1234567890', cost: 20 }] },
  { u: 'track dhl 1234567890', a: 'track', f: { trackingNumber: '1234567890' } },
  { u: 'ship ups 2 parcels to toronto', a: 'receipt', s: 'shipping', items: [{ city: 'Toronto', cost: null }] },
  { u: 'ship ups weight 2 kg to toronto', a: 'receipt', s: 'shipping', items: [{ cost: null }] },
  { u: 'ship ups to calgary T2P 1J9', a: 'receipt', s: 'shipping', keys: [], items: [{ city: 'Calgary', cost: null }] },
  { u: 'fed ex to calgary $20', a: 'receipt', s: 'shipping', items: [{ courier: 'FedEx', city: 'Calgary', cost: 20 }] },
  { u: 'ship from toronto to calgary AB $20', a: 'receipt', s: 'shipping', items: [{ city: 'Calgary', province: 'AB', cost: 20 }] },
  { u: 'ups to spruce grove ab $20', a: 'receipt', s: 'shipping', items: [{ city: 'Spruce Grove', province: 'AB', cost: 20 }] },
  { u: 'ups to Fort McMurray AB $20', a: 'receipt', s: 'shipping', items: [{ city: 'Fort McMurray', province: 'AB', cost: 20 }] },
  { u: 'ups to ON $20', a: 'receipt', s: 'shipping', items: [{ city: null, province: 'ON', cost: 20 }] },
  { u: 'refill for sarah hp 65 $34', a: 'receipt', s: 'refill', f: { customerName: 'Sarah', model: '65', price: 34 } },
  { u: 'refill for sarah phone 4035551212 $34', a: 'receipt', s: 'refill', f: { customerName: 'Sarah', customerPhone: '4035551212', price: 34 } },
  { u: "refill for anne-marie o'neill hp 65 $34", a: 'receipt', s: 'refill', f: { customerName: "Anne-Marie O'Neill" } },
  { u: 'refill for mary jane watson hp 65 $34', a: 'receipt', s: 'refill', f: { customerName: 'Mary Jane Watson' } },
  { u: 'sarah chen hp 65 refill $34', a: 'receipt', s: 'refill', f: { customerName: 'Sarah Chen', price: 34 } },
  { u: 'sold retractable pen $5', a: 'receipt', s: 'supplies', f: { supply: 'retractable pen', price: 5 } },
  { u: 'ups to toronto $22 plus box $5', a: 'receipt', s: 'shipping', segs: 1, pack: 1, items: [{ cost: 22 }] },
  { u: 'refill hp65 $34 plus print a label', a: 'receipt', s: 'refill', segs: 1, attach: { label: true } },
  { u: 'refill hp65 $34 then charge her card', a: 'receipt', s: 'refill', segs: 1, attach: { pay: true } },
  { u: 'note customer wants ink and toner refill tomorrow', a: 'note', segs: 1 },
  { u: 'refill hp 65 $34 and cut a kw1', segs: 2 },
  { u: 'key cut kw1 x2', a: 'receipt', s: 'key', keys: ['2xKW1'] },
  { u: 'cut 2 keys kw1 $10', a: 'receipt', s: 'key', keys: ['2xKW1'] },
  { u: 'cut key from B3 $5', a: 'receipt', s: 'key', keys: [], f: { price: 5 } },
  { u: 'add shift for sue 10-6 oct 8 with 30 min break', a: 'timesheet', op: 'add_shift', f: { employeeName: 'Sue', start: '10:00 AM', end: '6:00 PM' } },
  { u: 'sue worked 10-6 today', a: 'timesheet', op: 'adjust_shift', f: { employeeName: 'Sue', actualStart: '10:00 AM', actualEnd: '6:00 PM' } },
  { u: 'sue arrived 10:30 today', a: 'timesheet', op: 'adjust_shift', f: { employeeName: 'Sue', actualStart: '10:30' } },
  { u: 'sue finished 6 today', a: 'timesheet', op: 'adjust_shift', f: { employeeName: 'Sue', actualEnd: '6' } },
  { u: 'note printer ready set on shelf', a: 'note' },
  { u: 'note on shift printer failed', a: 'note' },
  { u: 'refill hp65 34.00', a: 'receipt', s: 'refill', f: { price: 34 } },
  { u: 'toner refil hp65 $34', a: 'receipt', s: 'refill', f: { price: 34 } },
  { u: 'ship 2 ups parcels to toronto $22 and calgary $30', a: 'receipt', s: 'shipping', items: [{ city: 'Toronto', cost: 22 }, { city: 'Calgary', cost: 30 }] },
  { u: 'ship ups $22 box $5 and box $7', a: 'receipt', s: 'shipping', pack: 2, known: 'a second box of the same kind, or "2 boxes", is not counted' },
  { u: 'add shift for sue oct 8-10 10-6', a: 'timesheet', op: 'add_shift', f: { days: 'Oct 8, 9, 10' }, known: 'a span of days ("oct 8-10") gives only its two ends' },
];


// Follow-ups: a slip is open (from `open`), then the counter types `say`. `edit`
// true means the message must change the open slip, false means it is a new ask.
// `f` / `items` are checked on the slip after the edit.
export const FOLLOWUPS = [
  {"open": "sue worked 10-6 today", "say": "actually 6:30", "edit": true, "f": {"employeeName": "Sue", "actualStart": "10:00 AM", "actualEnd": "6:30 PM"}},
  {"open": "sue worked 10-6 today", "say": "45 minute break", "edit": true, "f": {"employeeName": "Sue", "breakMinutes": 45}},
  {"open": "2 kw1", "say": "add 2 kw1", "edit": true, "keys": ["4xKW1"]},
  {"open": "note call bob", "say": "about paper", "edit": true, "f": {"content": "call bob about paper"}},
  {"open": "ups to toronto 22", "say": "actually dhl", "edit": true, "f": {"customerName": null}, "items": [{"courier": "DHL", "cost": 22, "city": "Toronto"}]},
  {"open": "ups to toronto 22", "say": "to paris france", "edit": true, "items": [{"city": "Paris", "province": "", "country": "France", "cost": 22}]},

  {"open": "2 kw1", "say": "add a sc1", "edit": true, "keys": ["2xKW1", "1xSC1"]},
  {"open": "2 kw1", "say": "and a y1", "edit": true, "keys": ["2xKW1", "1xY1"]},
  {"open": "2 kw1", "say": "plus 2 sc4", "edit": true, "keys": ["2xKW1", "2xSC4"]},
  {"open": "2 kw1", "say": "free", "edit": true, "f": {"price": 0}},
  {"open": "refill hp 65 $34", "say": "free", "edit": true, "f": {"price": 0}},
  {"open": "sold tape $5", "say": "free", "edit": true, "f": {"price": 0}},
  {"open": "ups to toronto 22", "say": "free", "edit": true, "f": {"price": 0}},
  {"open": "2 kw1", "say": "no charge", "edit": true, "f": {"price": 0}},
  {"open": "refill hp 65 $34", "say": "no charge", "edit": true, "f": {"price": 0}},
  {"open": "sold tape $5", "say": "no charge", "edit": true, "f": {"price": 0}},
  {"open": "ups to toronto 22", "say": "no charge", "edit": true, "f": {"price": 0}},
  {"open": "2 kw1", "say": "on the house", "edit": true, "f": {"price": 0}},
  {"open": "refill hp 65 $34", "say": "on the house", "edit": true, "f": {"price": 0}},
  {"open": "sold tape $5", "say": "on the house", "edit": true, "f": {"price": 0}},
  {"open": "ups to toronto 22", "say": "on the house", "edit": true, "f": {"price": 0}},
  {"open": "sue worked 10-6 today", "say": "actually 10:30", "edit": true, "f": {"employeeName": "Sue", "actualStart": "10:30 AM", "actualEnd": "6:00 PM"}},
  {"open": "sue worked 10-6 today", "say": "30 min break", "edit": true, "f": {"employeeName": "Sue", "breakMinutes": 30}},
  {"open": "sue worked 10-6 today", "say": "no wait it was mike", "edit": true, "op": "adjust_shift", "f": {"employeeName": "Mike", "actualStart": "10:00 AM", "actualEnd": "6:00 PM"}},
  {"open": "sue worked 10-6 today", "say": "it was mike", "edit": true, "op": "adjust_shift", "f": {"employeeName": "Mike", "actualStart": "10:00 AM", "actualEnd": "6:00 PM"}},
  {"open": "sue worked 10-6 today", "say": "for mike not sue", "edit": true, "op": "adjust_shift", "f": {"employeeName": "Mike", "actualStart": "10:00 AM", "actualEnd": "6:00 PM"}},
  {"open": "ups to toronto 22", "say": "actually fedex", "edit": true, "f": {"customerName": null}, "items": [{"courier": "FedEx", "city": "Toronto", "cost": 22}]},
  {"open": "ups to toronto 22", "say": "and another one to calgary 30", "edit": true, "items": [{"city": "Toronto", "cost": 22, "courier": "UPS"}, {"city": "Calgary", "cost": 30, "courier": "UPS"}]},
  {"open": "ups to toronto 22", "say": "another to calgary 30", "edit": true, "items": [{"city": "Toronto", "cost": 22, "courier": "UPS"}, {"city": "Calgary", "cost": 30, "courier": "UPS"}]},
  {"open": "ups to toronto 22", "say": "one more to calgary 30", "edit": true, "items": [{"city": "Toronto", "cost": 22, "courier": "UPS"}, {"city": "Calgary", "cost": 30, "courier": "UPS"}]},
  {"open": "ups to toronto 22", "say": "plus one to calgary 30", "edit": true, "items": [{"city": "Toronto", "cost": 22, "courier": "UPS"}, {"city": "Calgary", "cost": 30, "courier": "UPS"}]},
  {"open": "note call bob", "say": "about the toner", "edit": true, "f": {"content": "call bob about the toner"}},
  {"open": "note call bob", "say": "tomorrow", "edit": true, "f": {"content": "call bob tomorrow"}},

  { open: 'refill hp 65 $30', say: 'actually model 97', edit: true, f: { model: '97', price: 30 } },
  { open: 'refill hp 65 $30', say: 'model is 98', edit: true, f: { model: '98', price: 30 } },
  { open: 'record refill hp 65 for sarah', say: 'actually model 97', edit: true, f: { model: '97' } },
  { open: 'sold pens $10', say: 'quantity is 3', edit: true, f: { quantity: 3, price: 10 } },
  { open: 'sold pens $10', say: 'qty is 4', edit: true, f: { quantity: 4, price: 10 } },
  { open: 'cut 2 kw1 $5', say: 'three of them instead', edit: true, keys: ['3xKW1'], f: { price: 5 } },
  { open: 'cut 2 sc1 $6', say: 'four of those instead', edit: true, keys: ['4xSC1'], f: { price: 6 } },
  { open: 'ups to Toronto $22', say: 'to St. Albert AB', edit: true, items: [{ city: 'St. Albert', province: 'AB', cost: 22 }] },
  { open: 'refill hp 65 for sarah', say: '34', edit: true, f: { price: 34 } },
  { open: 'refill hp 65 for sarah $30', say: 'make it 40', edit: true, f: { price: 40 } },
  { open: 'refill hp 65 for sarah $30', say: 'actually 45', edit: true, f: { price: 45 } },
  { open: 'refill hp 65 for sarah $30', say: 'make it $40', edit: true, f: { price: 40, customerName: 'Sarah' } },
  { open: 'refill hp 65 for sarah $30', say: 'no tax', edit: true, f: { gst: false } },
  { open: 'refill hp 65 for sarah $30', say: 'no gst', edit: true, f: { gst: false } },
  { open: 'refill hp 65 for sarah $30', say: 'tax free', edit: true, f: { gst: false } },
  { open: 'refill hp 65 $30', say: '403 555 1212', edit: true, f: { customerPhone: '403 555 1212', price: 30 } },
  { open: 'refill hp 65 $30', say: 'her number is 4035551212', edit: true, f: { customerPhone: '4035551212', price: 30 } },
  { open: 'refill hp 65 $30', say: 'name is john smith', edit: true, f: { customerName: 'John Smith' } },
  { open: 'refill hp 65 $30', say: 'its for sarah', edit: true, f: { customerName: 'Sarah' } },
  { open: 'refill hp 65 $30', say: 'model is 65xl', edit: true, f: { model: '65XL', price: 30 } },
  { open: 'refill hp 65 $30', say: 'its a canon', edit: true, f: { brand: 'Canon' } },
  { open: 'refill $30', say: 'hp 65', edit: true, f: { brand: 'HP', model: '65', price: 30 } },
  { open: 'ups to toronto', say: '22', edit: true, items: [{ courier: 'UPS', city: 'Toronto', cost: 22 }] },
  { open: 'ups to toronto $22', say: 'change it to fedex', edit: true, items: [{ courier: 'FedEx', city: 'Toronto', cost: 22 }] },
  { open: 'ups to toronto $22', say: 'to calgary instead', edit: true, items: [{ courier: 'UPS', city: 'Calgary', province: 'AB', cost: 22 }] },
  { open: 'ups to toronto $22', say: 'add another fedex to vancouver $30', edit: true, items: [{ courier: 'UPS', cost: 22 }, { courier: 'FedEx', city: 'Vancouver', cost: 30 }] },
  { open: 'ups to toronto $22', say: 'sarah jones', edit: true, f: { customerName: 'Sarah Jones' } },
  { open: 'ups to toronto $22', say: 'add a box $5', edit: true, items: [{ cost: 22 }], pack: 1 },
  { open: 'ups to toronto $22', say: 'make it 25', edit: true, items: [{ cost: 25 }] },
  { open: 'sold a phone case', say: '10', edit: true, f: { price: 10, supply: 'phone case' } },
  { open: 'sold a phone case $10', say: '2 of them', edit: true, f: { quantity: 2 } },
  { open: 'sold a phone case $10', say: 'charge her card', edit: true, attach: { pay: true } },
  // A new ask while a slip is open is not an edit.
  { open: 'refill hp 65 $30', say: 'kw1?', edit: false },
  { open: 'refill hp 65 $30', say: 'who is working today', edit: false },
  { open: 'refill hp 65 $30', say: 'track fedex 123456789012', edit: false },
  { open: 'ups to toronto $22', say: 'note customer forgot id', edit: false },
  // From the second reader: a phone or tracking number must never become the price.
  { open: 'ship ups to toronto ON $22', say: 'phone is 4035551212', edit: true, f: { customerPhone: '4035551212' }, items: [{ cost: 22 }] },
  { open: 'refill for sarah hp65 $34', say: 'phone is 4035551212', edit: true, f: { customerPhone: '4035551212', price: 34 } },
  { open: 'ship ups to toronto ON $22', say: 'tracking is 123456789012', edit: true, items: [{ cost: 22, trackingNumber: '123456789012' }] },
];
